### ISSUE TITLE
Data: Taxonomies

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#11]
Create the `_data` files for each taxonomy below:

- [x] `categories.yml`
- [x] `keywords.yml`
- [x] `resources.yml`

`resources.yml` should be formatted like the following:
```yml
types:
  - Websites
  - Books

topics:
```

---
- [x] Create 2 test entries per file
