### ISSUE TITLE
Data: Issue Briefs

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#12]
- [x] Create a `_data` file to hold all the possible details information for the briefs. The file should be organized in the following way:

```yml
tech:
  type:
    - Unmanned Vehicles 
    - Platform Control and Information Support 
    - Sensors 
    - Cyber
    - Electronic Warfare
    - Space Platforms 
    - Miscellaneous
  characteristics:
    - Vantage/range
    - Speed
    - Resiliency 
    - Detectability 
    - Precision 
    - Persistence
  risk_factors:
    - Intrusive
    - Destructive
    - Predictive
    - Preemptive
    - Dual-use 
    - Clandestine
    - Vulnerable 
    - Action-enabling
  domain:
    - Land
    - Air 
    - Sea 
    - Space 
    - Cyberspace 
    - Multidomain 
  country:
    - United States
    - Russia
    - China
    - North Korea

countries:
```
