### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#16]
- [x] Create `_data/menus.yml` with links to the following pages:
  - [x] Issue Briefs
  - [x] Analysis
  - [x] Resources
  - [x] Workshops
  - [x] About
  - [x] Glossary

Each entry should have the following attributes:
- [x] url
- [x] title
- [x] identifier
- [x] inHeader
- [x] inFooter

*Example:*
```yml
- url: /issue-briefs/
  title: Issue Briefs
  identifier: briefs
  inHeader: true
  inFooter: true
```
- [x] Create `site-nav` include with a parameter for "class". The menu items should be rendered as an unordered list
