### ISSUE TITLE
Collection: Posts

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#5]
- [x] Create `posts` collection

- [x] Update `config.yml`
```yml
collections:
  posts:
    title: Analysis
    output: true

defaults:
- scope:
    path: ''
    type: 'posts'
  values:
    layout: post
    permalink: "/analysis/:slug/"
```
## Set up front matter templates in Forestry
  - [x] Title
  - [x] Date
  - [x] Excerpt
  - [x] Authors ("sortable list", pull from `authors` collection)
  - [x] Categories ("sortable list", pull from `categories` data file)
  - [x] Keywords ("sortable list", pull from `keywords` data file)
  - [x] Related Briefs ("sortable list", pull from `briefs` collection)
  - [x] Image
  - [x] Image Caption
  - [x] Image Source
