### ISSUE TITLE
Collection: Briefs

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#6]
- [x] Create `briefs` collection

- [x] Update `config.yml`
```yml
collections:
  briefs:
    title: Issue Briefs
    output: true

defaults:
- scope:
    path: ''
    type: 'briefs'
  values:
    layout: post
    permalink: "/issue-briefs/:slug/"
```
- [x] Create 2 test posts (one will be a tech primer and one will be a country profile)

## Set up front matter templates in Forestry
  - [x] Title
  - [x] Brief Type ("select field", options are: "Tech Primer" or "Country Profile")
  - [x] Date
  - [x] Excerpt
  - [x] Authors ("sortable list", pull from `authors` collection)
  - [x] Image
  - [x] Image Caption
  - [x] Image Source
  - [x] Details: This should be a [Field Group](https://forestry.io/docs/settings/fields/field-group/). Inside of the field group should be one sortable list per category under the 'tech' section of the `_data/briefs.yml` file. See #12 for details.
  - [x] Downloads: This should be a [Repeatable Field Group](https://forestry.io/docs/settings/fields/repeatable-field-group/). Inside of the field group there should be two fields: a text input for the `label` and a media upload for the `value`
