### ISSUE TITLE
Collection: Workshops

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#7]
Create `workshops` collection

- [x] Update `config.yml`
```yml
collections:
  workshops:
    title: Workshops
    output: true

defaults:
- scope:
    path: ''
    type: 'workshops'
  values:
    layout: post
    permalink: "/workshops/:slug/"
```
- [x] Create test post

## Set up front matter templates in Forestry
  - [x] Title
  - [x] Date
  - [x] Excerpt
  - [x] Authors ("sortable list", pull from `authors` collection)
  - [x] Image
  - [x] Image Caption
  - [x] Image Source
  - [x] Details: This should be a [Field Group](https://forestry.io/docs/settings/fields/field-group/)
     - [x] Event Date (date picker)
     - [x] Location (text input)
  - [x] Downloads: This should be a [Repeatable Field Group](https://forestry.io/docs/settings/fields/repeatable-field-group/). Inside of the field group there should be two fields: a text input for the `label` and a media upload for the `value`
