### ISSUE TITLE
Collection: Resources

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#8]
- [x] Create `resources` collection

- [x] Update `config.yml`
```yml
collections:
  resources:
    title: Resources
    output: false
```
- [x] Create test post

## Set up front matter templates in Forestry
  - [x] Title
  - [x] Type ("select field", pull from `_data/resources.yml` and the "type" heading)
  - [x] Authors ("textarea", no WYSIWYG)
  - [x] Topics ("sortable list field", pull from `_data/resources.yml` and the "topics" heading)
  - [x] URL (optional)
