### ISSUE TITLE
Collection: Authors

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/on-the-radar#9]
- [x] Create `authors` collection

- [x] Update `config.yml`
```yml
collections:
  authors:
    title: Authors
    output: true

defaults:
- scope:
    path: ''
    type: 'authors'
  values:
    layout: archive
    permalink: "/authors/:slug/"
```
- [x] Create test post

## Set up front matter templates in Forestry
  - [x] Title (The label in the UI should be "Name", but the field id is "title")
  - [x] Role (The label in the UI should be "Title", but the field id is "role")
